### ISSUE TITLE
BattleScribe 2.0

### ISSUE THREAD

**Issue by Jonskichov** [BSData/malifaux#4]
Hi guys.

BattleScribe 2.0 is coming and it contains some major changes to Data Editor and the data format.

While it should happily upgrade 1.15.x format data files to the new format, you never know what sneaky bugs might be lurking...

It would help a lot if you could run your data through it and make sure nothing gets broken so we have no nasty surprises on release day (whenever that might be...).

**Alpha Downloads:**
Desktop: https://github.com/BattleScribe/Desktop-Alphas/issues/1
Android: https://github.com/BattleScribe/Android-Alphas/issues/1
iOS: https://github.com/BattleScribe/iOS-Alphas/issues/1

If you find any issues, please do let me know: https://github.com/BattleScribe/Desktop-Alphas/issues

**Comment by reyzambo** [comment]
nice work. I'm new here and I just started by few days. you suggest to update to this version?

**Comment by amis92** [comment]
No no, absolutely don't do that now! The suggestion is, if you have spare time, to try it out. Which means, install 2.0 alpha, try to open/convert malifaux datafiles, check if everything works, and if not, report issue. But do not push these converted files to GitHub. The 2.0 is still alpha (not even beta) and these new files are incompatible with previous (1.15) version which everyone uses. There will come time for the conversion, but it is not this day. ;)

**Comment by reyzambo** [comment]
oook! I continue with my project, tnx :)

**Comment by Jonskichov** [comment]
@reyzambo Bear in mind that 2.0 will install alongside the existing version. It has a separate data folder, so you can just copy your files to that. You won't loose anything, just don't commit any changes you make with 2.0 to GitHub.

I'm going to reopen this to make sure it's visible to anyone else who wants to take a look.

**Comment by reyzambo** [comment]
ok I understand, for the moment I work to add models and factions on the project then I try to open all with alpha 2.0 when I have a "stable" version

cya

**Comment by Jonskichov** [comment]
@reyzambo Now's your time!
