### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by terryVL** [BSData/malifaux#5]
Hi,

I would like to join to help create a complete malifaux data set

**Comment by amis92** [comment]
Hello, @terryVL . Please accept the invitation in the email or on the [repo webpage](https://github.com/BSData/malifaux/invitations). Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Cheers!
